# Generated by Django 2.2 on 2023-01-24 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20230124_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='category',
        ),
        migrations.DeleteModel(
            name='categ',
        ),
        migrations.DeleteModel(
            name='products',
        ),
    ]
