# Generated by Django 2.2 on 2023-01-28 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='product',
            new_name='prodt',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='quantity',
            new_name='quant',
        ),
    ]
